modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="the_alca_chicken_mod"
version="1.0.0"
displayName="The ALCA Chicken Mod"
authors="Terrascotta, Israel"
description='''
Check out this GOOD mod for HONEST people!!!!!!!!
'''

[[dependencies.the_alca_chicken_mod]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.the_alca_chicken_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"